languageCode = "en-us"
theme = "mediumish-gohugo-theme"
title = ""
copyright = "Ming Hu - All wrongs reserved"
enableEmoji = true

[params]
logo = "/images/logo.png"

[params.social]
  github = "mingwho"
  linkedin = "ming-hu-codes"
  medium = "mingwho"
  instagram = "mingalchemist"

## Main Menu
[[menu.main]]
    name = "Case Study"
    weight = 100
    identifier = "case"
    url = "/case"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 300
    url = "/"
[[menu.main]]
    name = "Art"
    weight = 200
    identifier = "art"
    url = "/art"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 400
    url = "/static/imprint"

[params.index]
  picture = "/images/ming.jpg"
  title = "Ming Hu"
  subtitle = " "
  mdtext = '''
  Ming Hu remembers the black and white brush strokes of her childhood in China,
  those which formed the basis of Chinese calligraphy and ink landscapes.
  She also remembers the piles of puzzle books, brought by her parents,
  and inspired her to solve abstract problems with visual representation.
  It was here that her love for design and problem-solving was born.
  Her move to Abu Dhabi during her teenage years confirmed this initial enthusiasm,
  and her vocation began taking roots in the desert of Abu Dhabi.

  She studied computer science but sharpened her design skills at free time,
  working at Interactive Media Lab at NYU Abu Dhabi where she joined a circle
  of faculty and students who loved creating aesthetic and functional projects together.
  When she took the class Human and Machine with NYU Shanghai Professor Christian Grewell,
  it gave her the opportunity she needed to call upon her talents as a developer that
  understands the complications of art and technology. From there, she embarked on her
  adventure, working on projects of various media. Her vision of technology is the basis
  for her designs; she focuses on her favorite area of expression, the
  aesthetic-functionality equation and shares an indisputable pursuit of perfection
  with those she works with.
  Ming designs unambiguous experience to inspire the audience who appreciate the future of technology,
  only to be more scrutinous about it.
  '''

  alertbar = false

